version: 2
jobs:
  build:
    docker:
      - image: arednmesh/builder
    steps:
      - checkout
      - run:
          name: Generate changelog.md
          command: ssh ${SSH_USER}@${SSH_HOST} "sh -c 'docker run -it --rm -v ~/:/usr/local/src/your-app ferrarimarco/github-changelog-generator -u ${CIRCLE_PROJECT_USERNAME} -p ${CIRCLE_PROJECT_REPONAME} -t ${GITHUB_TOKEN}'"
      - run:
          name: Fetch README.md
          command: ssh ${SSH_USER}@${SSH_HOST} "sh -c 'wget https://raw.githubusercontent.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}/README.md'"

workflows:
  version: 2

  my_workflow:
    jobs:
      - build